apiVersion: v1
kind: Secret
metadata:
  name: jfrog-cred
  namespace: taxi
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ0YXhpMTEuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogIlUyRnBhM1Z0WVhKSE9rNWhkbVZsYmtBeE1qTT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
